id: PE4B8BBE8
initial_creation_type: input
source_metadata:
  title: Offering Series
  language: nl
  description: 'Lotsawa House presents the following texts related to the practice
    of offering (mchod pa):'
  volume:
    6b4e9f2417ff4a519324873fcf3ad548:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Eight Auspicious Substances
    03653e3695b845179022db6a447fa7d3:
      title: Teaching on the Offering of Flowers
      parent: Flower Offering
    2b43d5b656ec46edaec7878b51042880:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Garland of Offerings
    d0690f8ea67c4289b79cdc9d16e096be:
      title: Offering to the Nāgas of Gangtok
      parent: Offering to Nāgas
    2f156d6a99e2494d9bd3ed0f8ff2d15c:
      title: Töpa Gyatsoma Offering Prayer
      parent: Prayers
    b6c890136b2946ab9ed6fe32b64077c5:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      parent: Prayers
    15aacf8571fc406fbe66b49f15d41968:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prosperity
    f6c10e8ee43446a2905263bd0e6d0559:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    0e70968ef38c4d9ca76bf5e9f5ecec17:
      title: Brief Red Sur Offering
      parent: Sur Offering
    0229ebd13b904f7481010ee9cf1a07eb:
      title: Brief Sur Offering
      parent: Sur Offering
    332e9c18222a40f385d1400572ade28b:
      title: A Means of Offering Sur to the Damsi, Gyalgong and Others
      parent: Sur Offering
    7a08804f46e4400692f9b57c45cef2e1:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      parent: Sur Offering
    928dcd4dee7143389b55837044870851:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Water Offering
created_at: '2022-03-01T05:00:22.323969'
last_modified_at: '2022-03-01T05:00:22.323972'
